config/routes.rb
ApplicationItl::Application.routes.draw do
  devise_for :users
  resources :administrators

  resources :managers

  resources :categories

  resources :tasks do 
    collection { post :sorting}
  end

  root 'tasks#index'

end

app/models/administrator.rb
class Administrator < User
	
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :tasks
	
end

app/models/manager.rb
class Manager < User
	
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  has_attached_file :picture
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable

	has_many :tasks
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :set_administrator, only: [:show, :edit, :update, :destroy]

  # GET /administrators
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators
  def create
    @administrator = Administrator.new(administrator_params)

    if @administrator.save
      redirect_to @administrator, notice: 'Administrator was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /administrators/1
  def update
    if @administrator.update(administrator_params)
      redirect_to @administrator, notice: 'Administrator was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /administrators/1
  def destroy
    @administrator.destroy
    redirect_to administrators_url, notice: 'Administrator was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def administrator_params
      params.require(:administrator).permit(:firstname, :surname, :email, :phone)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :done_count

  def done_count
    @done_count = Task.find(:all, conditions: {done: true}).count
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: [:show, :edit, :update, :destroy]

  # GET /managers
  def index
    @managers = Manager.all
  end

  # GET /managers/1
  def show
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  def create
    @manager = Manager.new(manager_params)

    if @manager.save
      redirect_to @manager, notice: 'Manager was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /managers/1
  def update
    if @manager.update(manager_params)
      redirect_to @manager, notice: 'Manager was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /managers/1
  def destroy
    @manager.destroy
    redirect_to managers_url, notice: 'Manager was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def manager_params
      params.require(:manager).permit(:firstname, :surname, :email, :phone)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  def index
    @tasks = Task.order("sequence")
  end

  # GET /tasks/1
  def show
    if cookies['tasks'] 
      array = ActiveSupport::JSON.decode(cookies['tasks'])
    else
      array = Array.new
    end

    unless array.include?(@task.id)
      array << @task.id
    end
    cookies['tasks'] = ActiveSupport::JSON.encode(array)
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      respond_to do |format|
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.js
      end
    else
      render action: 'edit'
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.js
    end
  end

  def sorting
    params[:task].each_with_index do |id, index|
      Task.update_all(
        {sequence: index+1}, 
        {id: id}
      )
    end
    render nothing: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:user_id, :name, :done, :picture, :sequence, :'', :category_id)
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
	def read? task
		if cookies['tasks']
	    array = ActiveSupport::JSON.decode(cookies['tasks'])
			array.include?(task.id) ? "Read" : "Not Yet"
		else
			"Not Yet"
		end
  end
end

app/views/administrators/_form.html.erb
<%= form_for @administrator, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :firstname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :firstname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :surname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :surname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                administrators_path, :class => 'btn' %>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<%- model_class = Administrator -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/administrators/index.html.erb
<%- model_class = Administrator -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:firstname) %></th>
      <th><%= model_class.human_attribute_name(:surname) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @administrators.each do |administrator| %>
      <tr>
        <td><%= link_to administrator.id, administrator_path(administrator) %></td>
        <td><%= administrator.firstname %></td>
        <td><%= administrator.surname %></td>
        <td><%= administrator.email %></td>
        <td><%= administrator.phone %></td>
        <td><%= administrator.type %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_administrator_path(administrator), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      administrator_path(administrator),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_administrator_path,
            :class => 'btn btn-primary' %>

app/views/administrators/new.html.erb
<%- model_class = Administrator -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/administrators/show.html.erb
<%- model_class = Administrator -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:firstname) %>:</strong></dt>
  <dd><%= @administrator.firstname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:surname) %>:</strong></dt>
  <dd><%= @administrator.surname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @administrator.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @administrator.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @administrator.type %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              administrators_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_administrator_path(@administrator), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              administrator_path(@administrator),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                categories_path, :class => 'btn' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, category_path(category) %></td>
        <td><%= category.name %></td>
        <td><%=l category.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_category_path(category), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      category_path(category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path,
            :class => 'btn btn-primary' %>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @category.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              categories_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_category_path(@category), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApplicationItl</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="page-header">
	<h1><%= link_to "Simple Task list", root_url %></h1>
</div>

<ul class="breadcrumb">
  <li><%= link_to "Admins", administrators_path %><span class="divider">/</span></li>
  <li><%= link_to "Managers", managers_path %> <span class="divider">/</span></li>
  <li><%= link_to "Categories", categories_path %> <span class="divider">/</span></li>
  <li style="float:right">
		<% if user_signed_in? %>
		  Logged in as <strong><%= current_user.email %></strong>.
		  <%= link_to 'Edit profile', edit_user_registration_path %> |
		  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
		<% else %>
		  <%= link_to "Sign up", new_user_registration_path %> |
		  <%= link_to "Login", new_user_session_path %>
		<% end %>
	</li>
</ul>
<%= yield %>

</body>
</html>

app/views/managers/_form.html.erb
<%= form_for @manager, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :firstname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :firstname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :surname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :surname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                managers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<%- model_class = Manager -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/managers/index.html.erb
<%- model_class = Manager -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:firstname) %></th>
      <th><%= model_class.human_attribute_name(:surname) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= link_to manager.id, manager_path(manager) %></td>
        <td><%= manager.firstname %></td>
        <td><%= manager.surname %></td>
        <td><%= manager.email %></td>
        <td><%= manager.phone %></td>
        <td><%= manager.type %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_manager_path(manager), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      manager_path(manager),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_manager_path,
            :class => 'btn btn-primary' %>

app/views/managers/new.html.erb
<%- model_class = Manager -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/managers/show.html.erb
<%- model_class = Manager -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:firstname) %>:</strong></dt>
  <dd><%= @manager.firstname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:surname) %>:</strong></dt>
  <dd><%= @manager.surname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @manager.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @manager.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @manager.type %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              managers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_manager_path(@manager), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              manager_path(@manager),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/tasks/_form.html.erb
<%= form_for @task, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <% if user_signed_in? %>
      <%= f.hidden_field :user_id, value: current_user.id %>
  <% end %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :done, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :done, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :picture, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :picture, :class => 'file_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :category_id, Category.order(:name),:id,:name, include_blank: true %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tasks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<tr id="task_<%= task.id %>" style="width:100%">
  <td><%= link_to task.id, task_path(task) %></td>
  <td><%= read? task %></td>
  <td><%= task.user.try(:email) %></td>
  <td><%= link_to task.name, task_path(task) %></td>
  <td>
    <%= form_for task, remote: true do |f| %>
      <%= f.check_box :done, class: "task_done" %>
    <% end %>
  </td>
  <td><%= link_to task.try(:picture_file_name), task.try(:picture) ? task.picture.url : '' %></td>
  <td><%= task.category.try(:name) %></td>
  <td>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_task_path(task), :class => 'btn btn-mini' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                task_path(task),
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-mini btn-danger',
                remote: true %>
  </td>
</tr>

app/views/tasks/destroy.js.erb
$('#task_<%= @task.id %>').remove();

app/views/tasks/edit.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<%- model_class = Task -%>
<h4>done count:<div id="done_count"><%= @done_count %></div></h4>

<table class="table table-striped" id="tasks" data-sorting-url="<%= sorting_tasks_path %>">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= "Read" %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:done) %></th>
      <th><%= model_class.human_attribute_name(:picture) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <%= render task %>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_task_path,
            :class => 'btn btn-primary' %>

app/views/tasks/new.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <br/>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @task.user.try(:email) %> </dd>
  <br/>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @task.name %></dd>
  <br/>
  <dt><strong><%= model_class.human_attribute_name(:done) %>:</strong></dt>
  <dd><%= @task.done %></dd>
  <br/>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @task.category.try(:name) %></dd>
  <br/>
  <dt><strong><%= model_class.human_attribute_name(:picture) %>:</strong></dt>
  <dd><%= link_to @task.try(:picture_file_name), @task.try(:picture) ? @task.picture.url : '' %></dd>
  <br/>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tasks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_task_path(@task), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              task_path(@task),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/tasks/update.js.erb
$('#done_count').html('<%= Task.find(:all, conditions: {done: true}).count %>')